### ISSUE TITLE
Aerial opens a lot of invisible windows in ALT+TAB

### ISSUE THREAD

**Issue by tiaxter** [ChrisAnd1998/Aerial#8]
![image](https://user-images.githubusercontent.com/33230281/103469374-25bace80-4d64-11eb-8ef9-0e0316797337.png)

I'm using the latest version downloaded from this repo.

**Comment by GeorgeGedox** [comment]
Having the same issue. I've noticed that it creates a new invisible window for each instance that has reloaded the configuration if it makes sense.

**Comment by GeorgeGedox** [comment]
Found the issue, all instances of `FormBorderStyle` should be set to `FixedToolWindow` instead of `None`. As per the [documentation from Microsoft](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.formborderstyle?redirectedfrom=MSDN&view=net-5.0), this will hide the invisible window from the task switcher window.

I've created my own build with this fix but I can't do a pull request because this project does not seem to be properly setup for collaboration and the source tree will get really messy

**Comment by ChrisAnd1998** [comment]
@GeorgeGedox you're right George i will apply the fix for the next update ;)

**Comment by thedmmatt** [comment]
> Found the issue, all instances of `FormBorderStyle` should be set to `FixedToolWindow` instead of `None`. As per the [documentation from Microsoft](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.formborderstyle?redirectedfrom=MSDN&view=net-5.0), this will hide the invisible window from the task switcher window.
> 
> I've created my own build with this fix but I can't do a pull request because this project does not seem to be properly setup for collaboration and the source tree will get really messy

Hey @GeorgeGedox, do you mind sharing this build of yours? 😊

**Comment by ChrisAnd1998** [comment]
Sorry.. I should have fixed this a lot earlier. Thx @GeorgeGedox for the fix :)
https://github.com/ChrisAnd1998/Aerial/releases/tag/1.0.5.0
